### ISSUE TITLE
Where does (pm-set-buffer) come from?

### ISSUE THREAD

**Issue by Dima-369** [jingtaozf/literate-smalltalk#1]
Hey, I am trying this out and wondered about the definition of `(pm-set-buffer)` as I do not have it on Emacs 29.

Can you provide the definition in `literate-smalltalk.org`?

Some functions like `(literate-smalltalk-completion-candidates)` rely on it and I can't use them.

**Comment by Dima-369** [comment]
I suppose it is something like this?

```emacs-lisp
(defun pm-set-buffer (point)
    (switch-to-buffer (marker-buffer org-src--beg-marker))
    (goto-char point))
```

**Comment by jingtaozf** [comment]
It is a function in package polymode:
https://github.com/polymode/polymode/blob/master/polymode-core.el#L1146

**Comment by Dima-369** [comment]
Ah, I see. Thanks. I had trouble installing poly-org and so far everything worked pretty well without it.
