### ISSUE TITLE
Is this only compatible with some specific Pharo versions because I see some errors related to GTPlayground?

### ISSUE THREAD

**Issue by Dima-369** [jingtaozf/literate-smalltalk#3]
For instance, I am on Pharo 11.0 and `(company-literate-smalltalk-code)` shows this error in Pharo:

![image](https://user-images.githubusercontent.com/15002298/177704951-158dad49-0079-4df3-bdf1-fff528b4b762.png)

**Comment by jingtaozf** [comment]
I only test it in Pharo 9.
It's welcome to commit any patch to the latest Pharo, thanks.
