### ISSUE TITLE
Which version of the GTInspector package is used in Pharo 10?

### ISSUE THREAD

**Issue by vonHabsi** [jingtaozf/literate-smalltalk#5]
I get a lot of debug messages like

`		stepContents: 	'LiterateServer class>>apiEvalBindings: (GTInspector is Undeclare...etc...`

so I suspect your code depends on the GTInspect package which is not built into Pharo 10.

However when I try to install GTInspector virtually the whole of Glamorous Toolkit gets pulled in so I suspect it must be a different GTInspector from the current feenkcom version.

Any idea where I can install it from?

**Comment by jingtaozf** [comment]
@vonHabsi Actually we don't need to install additional toolkit as Pharo 10 also has a native inspector StInspector.
I added a commit to use it if possible in Pharo:
https://github.com/jingtaozf/literate-smalltalk/commit/f8813d8a510a9f0bf6d1ae6c1e90f154ea2f799b

**Comment by vonHabsi** [comment]
Thanks for the update.

I will give it a try and report back.

I'm a Pharo newbie so please bear with me.
